export const coursesList = [
  {
    head: "Popular Courses",
    options: [
      {
        id: 18,
        text: "BE/B.Tech - Bachelors (Technology)",
        stream_id: 10,
        course_tag: "BE/B.Tech",
        course_tag_type: "Bachelors",
        url: "btech-courses",
        child_options: [
          {
            mode: false,
            coaching: true,
            study_abroad: true,
            loan_assistance: true,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 120,
        text: "MBA/PGDM - Masters (Business Administration)",
        stream_id: 13,
        course_tag: "MBA/PGDM",
        course_tag_type: "Masters",
        url: "mba-courses",
        child_options: [
          {
            mode: true,
            coaching: true,
            study_abroad: true,
            loan_assistance: true,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 15,
        text: "BBA/BBM - Bachelors (Business Administration)",
        stream_id: 13,
        course_tag: "BBA/BBM",
        course_tag_type: "Bachelors",
        url: "bba-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 2,
        text: "B.Com - Bachelors (Commerce)",
        stream_id: 5,
        course_tag: "B.Com",
        course_tag_type: "Bachelors",
        url: "bcom-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 12,
        text: "BA - Bachelors (Arts)",
        stream_id: 3,
        course_tag: "BA",
        course_tag_type: "Bachelors",
        url: "ba-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 117,
        text: "MA - Masters (Arts)",
        stream_id: 3,
        course_tag: "MA",
        course_tag_type: "Masters",
        url: "ma-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 121,
        text: "MBBS - Bachelors (Medicince and Surgery)",
        stream_id: 6,
        course_tag: "MBBS",
        course_tag_type: "Bachelors",
        url: "mbbs-courses",
        child_options: [
          {
            mode: true,
            coaching: true,
            study_abroad: true,
            loan_assistance: true,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 16,
        text: "BCA - Bachelors (Computer Applications)",
        stream_id: 6,
        course_tag: "BCA",
        course_tag_type: "Bachelors",
        url: "bca-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 122,
        text: "MCA - Masters (Computer Applications)",
        stream_id: 10,
        course_tag: "MCA",
        course_tag_type: "Masters",
        url: "mca-courses",
        child_options: [
          {
            mode: true,
            coaching: true,
            study_abroad: true,
            loan_assistance: true,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 125,
        text: "ME/M.Tech - Masters (Technology)",
        stream_id: 18,
        course_tag: "ME/M.Tech",
        course_tag_type: "Masters",
        url: "mtech-courses",
        child_options: [
          {
            mode: true,
            coaching: true,
            study_abroad: true,
            loan_assistance: true,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 6,
        text: "B.Sc - Bachelors (Science)",
        stream_id: 18,
        course_tag: "B.Sc",
        course_tag_type: "Bachelors",
        url: "bsc-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 111,
        text: "M.Sc - Masters (Science)",
        stream_id: 18,
        course_tag: "M.Sc",
        course_tag_type: "Masters",
        url: "msc-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
    ],
  },
  {
    head: "Bachelor",
    options: [
      {
        id: 212,
        text: "BS - Bachelor (Science)",
        stream_id: 18,
        course_tag: "BS",
        course_tag_type: "Bachelor",
        url: null,
        child_options: [
          {
            mode: false,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 211,
        text: "BA LLB - Bachelor (Law)",
        stream_id: 12,
        course_tag: "BA LLB",
        course_tag_type: "Bachelor",
        url: null,
        child_options: [
          {
            mode: false,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 83,
        text: "LLB - Bachelor (Law)",
        stream_id: 12,
        course_tag: "LLB",
        course_tag_type: "Bachelor",
        url: "llb-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 206,
        text: "Bachelor of Animation - Bachelor (Animation)",
        stream_id: 1113,
        course_tag: "Bachelor of Animation",
        course_tag_type: "Bachelor",
        url: "bachelor-of-animation-courses",
        child_options: [
          {
            mode: false,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 205,
        text: "BSW - Bachelor (Arts)",
        stream_id: 3,
        course_tag: "BSW",
        course_tag_type: "Bachelor",
        url: "bsw-courses",
        child_options: [
          {
            mode: false,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 203,
        text: "BPH - Bachelor (Medical)",
        stream_id: 15,
        course_tag: "BPH",
        course_tag_type: "Bachelor",
        url: null,
        child_options: [
          {
            mode: false,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 200,
        text: "B.F.Sc - Bachelor (Science)",
        stream_id: 18,
        course_tag: "B.F.Sc",
        course_tag_type: "Bachelor",
        url: null,
        child_options: [
          {
            mode: false,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 197,
        text: "Bachelors (Animation & Graphic Design) - Bachelor (Arts)",
        stream_id: 3,
        course_tag: "Bachelors (Animation & Graphic Design)",
        course_tag_type: "Bachelor",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 195,
        text: "BBA (Aviation) - Bachelor (Aviation)",
        stream_id: 4,
        course_tag: "BBA (Aviation)",
        course_tag_type: "Bachelor",
        url: "bba-aviation-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 194,
        text: "B.P.Ed - Bachelor (Education)",
        stream_id: 9,
        course_tag: "B.P.Ed",
        course_tag_type: "Bachelor",
        url: "bped-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 193,
        text: "BFA - Bachelor (Arts)",
        stream_id: 3,
        course_tag: "BFA",
        course_tag_type: "Bachelor",
        url: "bfa-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 190,
        text: "BUMS - Bachelor (Medical)",
        stream_id: 15,
        course_tag: "BUMS",
        course_tag_type: "Bachelor",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 189,
        text: "Bachelor of Physiotherapy(BPT) - Bachelor (Medical)",
        stream_id: 15,
        course_tag: "Bachelor of Physiotherapy(BPT)",
        course_tag_type: "Bachelor",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 188,
        text: "B.Planning - Bachelor (Architecture)",
        stream_id: 2,
        course_tag: "B.Planning",
        course_tag_type: "Bachelor",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 187,
        text: "BHMS - Bachelor (Medical)",
        stream_id: 15,
        course_tag: "BHMS",
        course_tag_type: "Bachelor",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 213,
        text: "BHM (Hospital) - Bachelor (Management)",
        stream_id: 13,
        course_tag: "BHM (Hospital)",
        course_tag_type: "Bachelor",
        url: null,
        child_options: [
          {
            mode: false,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 21,
        text: "BVSc - Bachelor (Veterinary Sciences)",
        stream_id: 19,
        course_tag: "BVSc",
        course_tag_type: "Bachelor",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 20,
        text: "BMM - Bachelor (Mass Communications)",
        stream_id: 14,
        course_tag: "BMM",
        course_tag_type: "Bachelor",
        url: "bmm-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 10,
        text: "B.Sc (Medicine) - Bachelor (Medical)",
        stream_id: 15,
        course_tag: "B.Sc (Medicine)",
        course_tag_type: "Bachelor",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 7,
        text: "B.Sc (Agriculture) - Bachelor (Agriculture)",
        stream_id: 1,
        course_tag: "B.Sc (Agriculture)",
        course_tag_type: "Bachelor",
        url: "bsc-agriculture-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 5,
        text: "B.Pharm - Bachelor (Pharmacy)",
        stream_id: 17,
        course_tag: "B.Pharm",
        course_tag_type: "Bachelor",
        url: "bpharm-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 4,
        text: "B.Ed - Bachelor (Education)",
        stream_id: 9,
        course_tag: "B.Ed",
        course_tag_type: "Bachelor",
        url: "bed-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 3,
        text: "B.Des - Bachelor (Design)",
        stream_id: 8,
        course_tag: "B.Des",
        course_tag_type: "Bachelor",
        url: "bdes-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 1,
        text: "B.Arch - Bachelor (Architecture)",
        stream_id: 2,
        course_tag: "B.Arch",
        course_tag_type: "Bachelor",
        url: "barch-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 11,
        text: "B.Sc (Nursing) - Bachelor (Paramedical)",
        stream_id: 16,
        course_tag: "B.Sc (Nursing)",
        course_tag_type: "Bachelor",
        url: "bsc-nursing-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 19,
        text: "BHM - Bachelor (Hotel Management)",
        stream_id: 11,
        course_tag: "BHM",
        course_tag_type: "Bachelor",
        url: "bhm-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 17,
        text: "BDS - Bachelor (Dental)",
        stream_id: 7,
        course_tag: "BDS",
        course_tag_type: "Bachelor",
        url: "bds-courses",
        child_options: [
          {
            mode: true,
            coaching: true,
            study_abroad: true,
            loan_assistance: true,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 14,
        text: "BAMS - Bachelor (Medical)",
        stream_id: 15,
        course_tag: "BAMS",
        course_tag_type: "Bachelor",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 13,
        text: "Bachelors in Vocational Courses - Bachelor (Vocational Courses)",
        stream_id: 20,
        course_tag: "Bachelors in Vocational Courses",
        course_tag_type: "Bachelor",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
    ],
  },
  {
    head: "Masters",
    options: [
      {
        id: 192,
        text: "M.P.Ed - Masters (Education)",
        stream_id: 9,
        course_tag: "M.P.Ed",
        course_tag_type: "Masters",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 199,
        text: "MMS - Masters (Management)",
        stream_id: 13,
        course_tag: "MMS",
        course_tag_type: "Masters",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 91,
        text: "M.Pharm - Masters (Pharmacy)",
        stream_id: 17,
        course_tag: "M.Pharm",
        course_tag_type: "Masters",
        url: "mpharm-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 90,
        text: "M.Ed - Masters (Education)",
        stream_id: 9,
        course_tag: "M.Ed",
        course_tag_type: "Masters",
        url: "med-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 48,
        text: "Executive MBA - Masters (Management)",
        stream_id: 13,
        course_tag: "Executive MBA",
        course_tag_type: "Masters",
        url: "executive-mba-courses",
        child_options: [
          {
            mode: true,
            coaching: true,
            study_abroad: true,
            loan_assistance: true,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 89,
        text: "M.Des - Masters (Design)",
        stream_id: 8,
        course_tag: "M.Des",
        course_tag_type: "Masters",
        url: "mdes-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 207,
        text: "Master of Animation - Masters (Animation)",
        stream_id: 1113,
        course_tag: "Master of Animation",
        course_tag_type: "Masters",
        url: null,
        child_options: [
          {
            mode: false,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 88,
        text: "M.Com - Masters (Commerce)",
        stream_id: 5,
        course_tag: "M.Com",
        course_tag_type: "Masters",
        url: "mcom-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 85,
        text: "LLM - Masters (Law)",
        stream_id: 12,
        course_tag: "LLM",
        course_tag_type: "Masters",
        url: "llm-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 201,
        text: "M.F.Sc - Masters (Science)",
        stream_id: 18,
        course_tag: "M.F.Sc",
        course_tag_type: "Masters",
        url: null,
        child_options: [
          {
            mode: false,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 202,
        text: "MPH - Masters (Medical)",
        stream_id: 15,
        course_tag: "MPH",
        course_tag_type: "Masters",
        url: null,
        child_options: [
          {
            mode: false,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 87,
        text: "M.Ch - Masters (Medical)",
        stream_id: 15,
        course_tag: "M.Ch",
        course_tag_type: "Masters",
        url: "pg-medical-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 204,
        text: "MSW - Masters (Arts)",
        stream_id: 3,
        course_tag: "MSW",
        course_tag_type: "Masters",
        url: null,
        child_options: [
          {
            mode: false,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 86,
        text: "M.Arch - Masters (Architecture)",
        stream_id: 2,
        course_tag: "M.Arch",
        course_tag_type: "Masters",
        url: "march-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 191,
        text: "MHA - Masters (Management)",
        stream_id: 13,
        course_tag: "MHA",
        course_tag_type: "Masters",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 112,
        text: "M.Sc (Agriculture) - Masters (Agriculture)",
        stream_id: 1,
        course_tag: "M.Sc (Agriculture)",
        course_tag_type: "Masters",
        url: "msc-agriculture-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 113,
        text: "M.Sc (Aviation) - Masters (Aviation)",
        stream_id: 4,
        course_tag: "M.Sc (Aviation)",
        course_tag_type: "Masters",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 115,
        text: "M.Sc (Medicine) - Masters (Medical)",
        stream_id: 15,
        course_tag: "M.Sc (Medicine)",
        course_tag_type: "Masters",
        url: "pg-medical-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 116,
        text: "M.Sc (Nursing) - Masters (Paramedical)",
        stream_id: 16,
        course_tag: "M.Sc (Nursing)",
        course_tag_type: "Masters",
        url: "msc-nursing-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 118,
        text: "Master of Physiotherapy(MPT) - Masters (Medical)",
        stream_id: 15,
        course_tag: "Master of Physiotherapy(MPT)",
        course_tag_type: "Masters",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 119,
        text: "Masters in Vocational Courses - Masters (Vocational Courses)",
        stream_id: 20,
        course_tag: "Masters in Vocational Courses",
        course_tag_type: "Masters",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 124,
        text: "MDS - Masters (Dental)",
        stream_id: 7,
        course_tag: "MDS",
        course_tag_type: "Masters",
        url: "mds-courses",
        child_options: [
          {
            mode: true,
            coaching: true,
            study_abroad: true,
            loan_assistance: true,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 126,
        text: "MHM - Masters (Hotel Management)",
        stream_id: 11,
        course_tag: "MHM",
        course_tag_type: "Masters",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 127,
        text: "MMC - Masters (Mass Communications)",
        stream_id: 14,
        course_tag: "MMC",
        course_tag_type: "Masters",
        url: "mmc-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 128,
        text: "MS - Masters (Medical)",
        stream_id: 15,
        course_tag: "MS",
        course_tag_type: "Masters",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 129,
        text: "MVSc - Masters (Veterinary Sciences)",
        stream_id: 19,
        course_tag: "MVSc",
        course_tag_type: "Masters",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 110,
        text: "M.Planning - Masters (Architecture)",
        stream_id: 2,
        course_tag: "M.Planning",
        course_tag_type: "Masters",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
    ],
  },
  {
    head: "Doctorate",
    options: [
      {
        id: 123,
        text: "MD - Doctorate (Medical)",
        stream_id: 15,
        course_tag: "MD",
        course_tag_type: "Doctorate",
        url: "pg-medical-courses",
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 156,
        text: "Ph.D in Veterinary Science - Doctorate (Veterinary Sciences)",
        stream_id: 19,
        course_tag: "Ph.D in Veterinary Science",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 109,
        text: "M.Phil/Ph.D in Science - Doctorate (Science)",
        stream_id: 18,
        course_tag: "M.Phil/Ph.D in Science",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 108,
        text: "M.Phil/Ph.D in Pharmacy - Doctorate (Pharmacy)",
        stream_id: 17,
        course_tag: "M.Phil/Ph.D in Pharmacy",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 107,
        text: "M.Phil/Ph.D in Paramedical - Doctorate (Paramedical)",
        stream_id: 16,
        course_tag: "M.Phil/Ph.D in Paramedical",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 106,
        text: "M.Phil/Ph.D in Medicine - Doctorate (Medical)",
        stream_id: 15,
        course_tag: "M.Phil/Ph.D in Medicine",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 105,
        text: "M.Phil/Ph.D in Mass Communication - Doctorate (Mass Communications)",
        stream_id: 14,
        course_tag: "M.Phil/Ph.D in Mass Communication",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 96,
        text: "M.Phil/Ph.D in Commerce - Doctorate (Commerce)",
        stream_id: 5,
        course_tag: "M.Phil/Ph.D in Commerce",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 97,
        text: "M.Phil/Ph.D in Computer Applications - Doctorate (Computer Applications)",
        stream_id: 6,
        course_tag: "M.Phil/Ph.D in Computer Applications",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 98,
        text: "M.Phil/Ph.D in Dental - Doctorate (Dental)",
        stream_id: 7,
        course_tag: "M.Phil/Ph.D in Dental",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 94,
        text: "M.Phil/Ph.D in Architecture - Doctorate (Architecture)",
        stream_id: 2,
        course_tag: "M.Phil/Ph.D in Architecture",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 93,
        text: "M.Phil/Ph.D in Agriculture - Doctorate (Agriculture)",
        stream_id: 1,
        course_tag: "M.Phil/Ph.D in Agriculture",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 99,
        text: "M.Phil/Ph.D in Design - Doctorate (Design)",
        stream_id: 8,
        course_tag: "M.Phil/Ph.D in Design",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 100,
        text: "M.Phil/Ph.D in Education - Doctorate (Education)",
        stream_id: 9,
        course_tag: "M.Phil/Ph.D in Education",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 101,
        text: "M.Phil/Ph.D in Engineering - Doctorate (Engineering)",
        stream_id: 10,
        course_tag: "M.Phil/Ph.D in Engineering",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 95,
        text: "M.Phil/Ph.D in Arts - Doctorate (Arts)",
        stream_id: 3,
        course_tag: "M.Phil/Ph.D in Arts",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 104,
        text: "M.Phil/Ph.D in Management - Doctorate (Management)",
        stream_id: 13,
        course_tag: "M.Phil/Ph.D in Management",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 103,
        text: "M.Phil/Ph.D in Law - Doctorate (Law)",
        stream_id: 12,
        course_tag: "M.Phil/Ph.D in Law",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 102,
        text: "M.Phil/Ph.D in Hotel Management - Doctorate (Hotel Management)",
        stream_id: 11,
        course_tag: "M.Phil/Ph.D in Hotel Management",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
      {
        id: 34,
        text: "D.Litt - Doctorate (Arts)",
        stream_id: 3,
        course_tag: "D.Litt",
        course_tag_type: "Doctorate",
        url: null,
        child_options: [
          {
            mode: true,
            coaching: false,
            study_abroad: false,
            loan_assistance: false,
          },
        ],
        is_selected: false,
        class: "",
      },
    ],
  },
];
